/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mjtech_com_ng;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author jamil
 */
public class RegisteredUsers extends javax.swing.JFrame {
    private static final String USERNAME = "root";
    private static final String PASSWORD = "";
    private static final String DATABASE_NAME = "jdbc:mysql://localhost/cultural_song";
    private Connection conn = null;
    private Statement st = null;
    String[][] data1 = new String[200][19];

    /**
     * Creates new form RegisteredUsers
     */
    public RegisteredUsers() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        displayUsersList();
    }
    
    public void connect() {
        try {
            conn = DriverManager.getConnection(DATABASE_NAME, USERNAME, PASSWORD);
            st = conn.createStatement();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Could not connect to database! \n Error: " + ex, "Status", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void displayUsersList(){
        int row = 0;
        try {
            String query = "select fullname, gender, email, phone, username, created_on from users ORDER by fullname, created_on ASC";
            connect();
            st.executeQuery(query);
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                for (int i = 0; i < 6;i++) {
                    int q = i + 1;
                    data1[row][i] = rs.getString(q);
                }
                row++;
            }
            rs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        Object[][]data2 = new Object[row][6];
        for(int i = 0;i<row;i++) {
            System.arraycopy(data1[i], 0, data2[i], 0,6);
        }
        final Object[] Column = {"Fullname", "Gender", "Email", "Phone", "Username", "Date Join"};
        usersRecordTable.setModel(new javax.swing.table.DefaultTableModel(data2,Column));
        usersRecordTable.setShowHorizontalLines(false);
        usersRecordTable.setShowVerticalLines(false);
   }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersRecordTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        musicReportTab = new javax.swing.JLabel();
        musicRegTab = new javax.swing.JLabel();
        logoutTab = new javax.swing.JLabel();
        userReportTab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registered Users");

        usersRecordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fullname", "Gender", "Email", "Phone", "Username", "Date Join"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usersRecordTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(usersRecordTable);

        musicReportTab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        musicReportTab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        musicReportTab.setText("Music Report");
        musicReportTab.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)), null));
        musicReportTab.setOpaque(true);
        musicReportTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musicReportTabMouseClicked(evt);
            }
        });

        musicRegTab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        musicRegTab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        musicRegTab.setText("Music Registration");
        musicRegTab.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)), null));
        musicRegTab.setOpaque(true);
        musicRegTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musicRegTabMouseClicked(evt);
            }
        });

        logoutTab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutTab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutTab.setText("Logout");
        logoutTab.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)), null));
        logoutTab.setOpaque(true);
        logoutTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutTabMouseClicked(evt);
            }
        });

        userReportTab.setBackground(new java.awt.Color(255, 255, 255));
        userReportTab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userReportTab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userReportTab.setText("Users Report");
        userReportTab.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)), null));
        userReportTab.setOpaque(true);
        userReportTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userReportTabMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(musicRegTab, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(musicReportTab, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userReportTab, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logoutTab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musicReportTab, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutTab, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userReportTab, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musicRegTab, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void musicReportTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicReportTabMouseClicked
        RegisteredMusic music_report = new RegisteredMusic();
        music_report.show();
        this.dispose();
    }//GEN-LAST:event_musicReportTabMouseClicked

    private void musicRegTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicRegTabMouseClicked
        MusicRegistration music_reg = new MusicRegistration();
        music_reg.show();
        this.dispose();
    }//GEN-LAST:event_musicRegTabMouseClicked

    private void logoutTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutTabMouseClicked
        int status = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (status == JOptionPane.YES_OPTION) {
            Login login = new Login();
            login.show();
            this.dispose();
        }
    }//GEN-LAST:event_logoutTabMouseClicked

    private void userReportTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userReportTabMouseClicked
        JOptionPane.showMessageDialog(this, "You're already on the form!", 
                "Status", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_userReportTabMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisteredUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisteredUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisteredUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisteredUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisteredUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoutTab;
    private javax.swing.JLabel musicRegTab;
    private javax.swing.JLabel musicReportTab;
    private javax.swing.JLabel userReportTab;
    private javax.swing.JTable usersRecordTable;
    // End of variables declaration//GEN-END:variables
}
